kind: Secret
apiVersion: v1
metadata:
  name: database
  labels:
    app: db
type: Opaque
stringData:
  DB_USER: unblu
  DB_PASSWORD: "KWQBq6KmnaffK5CEaUGuhDqv"
  DB_ADMIN_USER: "unblu_admin"
  DB_ADMIN_PASSWORD: "EYqMtzLtXRPhKdMJ65bEUtXV"
