apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db
  # TODO rename to maria-data ?
  name: mysql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9104"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: mariadb
          image: mariadb
          imagePullPolicy: Always
          env:
          - name: "MYSQL_USER"
            valueFrom:
              secretKeyRef:
                name: database
                key: DB_USER
          - name: "MYSQL_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: database
                key: DB_PASSWORD
          - name: "MYSQL_ROOT_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: database
                key: DB_ADMIN_PASSWORD
          - name: "MYSQL_DATABASE"
            value: "unblu"
          args:
          - --character-set-server=utf8
          - --collation-server=utf8_general_ci
          - --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
          - --ignore-db-dir=lost+found
          - --max_allowed_packet=32M
          - --max_connections=300
          - --wait_timeout=28800
          ports:
          - containerPort: 3306
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
        - name: mariadb-exporter
          image: prom/mysqld-exporter
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: database
                  key: DB_ADMIN_PASSWORD
            - name: DATA_SOURCE_NAME
              value: root:$(MYSQL_ROOT_PASSWORD)@/
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 64Mi
          ports:
            - containerPort: 9104
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: mariadb
spec:
  ports:
  - name: 3306-tcp
    port: 3306
  selector:
    app: db
  type: ClusterIP
