apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: main-entry
  annotations:
    haproxy.router.openshift.io/timeout: 300s
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: nginx
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
