apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-ingress
spec:
  tls:
  - secretName: ingress-tls
    hosts:
    - example.unblu-test.com
  backend:
    serviceName: nginx
    servicePort: 8080