apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-openshift

bases: 
# TODO change path to pull bases from GitHub
# - github.com/unblu-inc/unblu-kubernetes-base//collaboration-server
- ../collaboration-server
- ../renderingservice
- ../openshift-prometheus
- ../grafana
- ../openshift-route

patchesStrategicMerge:
- route.yaml
- limit-resources.yaml

resources:
- database-secret.yaml

configMapGenerator:
- name: collaboration-server-config
  behavior: merge
  files:
    - unblu-customer.properties

