{
 "title": "Zookeeper",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(zookeeper_data_bytes{component = \"zookeeper\", kubernetes_pod_name=\"zookeeper-0\"})",
     "legendFormat": "zookeper-0"
    },
    {
     "expr": "avg(zookeeper_data_bytes{component = \"zookeeper\", kubernetes_pod_name=\"zookeeper-1\"})",
     "legendFormat": "zookeeper-1"
    },
    {
     "expr": "avg(zookeeper_data_bytes{component = \"zookeeper\", kubernetes_pod_name=\"zookeeper-2\"})",
     "legendFormat": "zookeeper-2"
    }
   ]
  },
  {
   "title": "Packets I/O",
   "type": "graph",
   "description": "Total amount of packets sent vs packets received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zookeeper_packets_received_total[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(zookeeper_packets_sent_total[1m]))",
     "legendFormat": "Sent"
    },
    {}
   ]
  },
  {
   "title": "Alive Client Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (kubernetes_pod_name) (zookeeper_aliveClientConnections)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Pending Session Revalidations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_syncs_pending",
     "legendFormat": "{{kubernetes_pod_name}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "graph",
   "description": "Max latency for each of the zookeeper pods",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "zookeeper_latency_max_milliseconds",
     "legendFormat": "{{kubernetes_pod_name}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.AvgRequestLatency, 4, 6)"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_requests_outstanding_requests",
     "legendFormat": "{{kubernetes_pod_name}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  { "title": "Zookeeper Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Max Proposal Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "ticks" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (zookeeper_proposalSize_max)",
     "legendFormat": "{{kubernetes_pod_name}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.AvgRequestLatency, 4, 6)"
    }
   ]
  },
  {
   "title": "Zookeeper Leader",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_isleader{component=\"zookeeper\"}",
     "legendFormat": "{{kubernetes_pod_name}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  {
   "title": "Watches",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_watches", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Followers",
   "type": "graph",
   "description": "Zookeeper followers count",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_followers",
     "legendFormat": "{{kubernetes_pod_name}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    },
    {}
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{component=\"zookeeper\", area=\"heap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{component=\"zookeeper\", area=\"heap\"}) ",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{component=\"zookeeper\", area=\"heap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Log events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (level) (increase(logback_events_total{component=\"zookeeper\"}[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_memory_swap_bytes{component=\"zookeeper\"})",
     "legendFormat": "swap"
    },
    {
     "expr": "sum(process_memory_swappss_bytes{component=\"zookeeper\"})",
     "legendFormat": "swappss"
    },
    {
     "expr": "sum(process_memory_pss_bytes{component=\"zookeeper\"}) + sum(process_memory_swap_bytes{component=\"zookeeper\"})",
     "legendFormat": "phys (pss+swap)"
    }
   ]
  }
 ]
}