{
 "title": "Video Rendering",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "browserid",
    "label": "Browser ID",
    "query": "label_values(venc_measured_bitrate, browser_id)"
   }
  ]
 },
 "panels": [
  { "title": "Bitrates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bits sent over the wire",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "venc_measured_bitrate{browser_id=~\"$browserid\"}",
     "legendFormat": "{{browser_id}}"
    }
   ]
  },
  {
   "title": "WebRTC Desired Bitrate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "venc_feedback_bitrate{browser_id=~\"$browserid\"}",
     "legendFormat": " {{browser_id}}"
    }
   ]
  },
  {
   "title": "Bitrate boost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "venc_bitrate_boost{browser_id=~\"$browserid\"}",
     "legendFormat": "venc_bitrate_boost"
    }
   ]
  },
  { "title": "Frames", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Measured Frame Quality",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "venc_measured_frame_quality{browser_id=~\"$browserid\"}",
     "legendFormat": "{{browser_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Frame time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "venc_measured_frame_time{browser_id=~\"$browserid\"}",
     "legendFormat": "{{browser_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "WebRTC Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(webrtc_outbound_rtp_fir_count{kind=\"video\",browser_id=~\"$browserid\"}[2s])",
     "legendFormat": "Full Intra Request - {{browser_id}}"
    },
    {
     "expr": "delta(webrtc_outbound_rtp_pli_count{kind=\"video\",browser_id=~\"$browserid\"}[2s])",
     "legendFormat": "Picture Loss Indication - {{browser_id}}"
    },
    {
     "expr": "delta(webrtc_outbound_rtp_nack_count{kind=\"video\",browser_id=~\"$browserid\"}[2s])",
     "legendFormat": "Negative Acknowledgement - {{browser_id}}"
    },
    {
     "expr": "delta(webrtc_outbound_rtp_sli_count{kind=\"video\",browser_id=~\"$browserid\"}[2s])",
     "legendFormat": "Slice Loss Indication - {{browser_id}}"
    }
   ]
  },
  {
   "title": "Frame quality variance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "venc_measured_frame_quality_variance{browser_id=~\"$browserid\"}",
     "legendFormat": "{{browser_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Feedback Framerate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "venc_feedback_frame_rate{browser_id=~\"$browserid\"}",
     "legendFormat": "venc_feedback_frame_rate - {{browser_id}}"
    }
   ]
  },
  {
   "title": "Round Trip Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "webrtc_ice_candidate_pair_current_round_trip_time{browser_id=~\"$browserid\"}",
     "legendFormat": "round_trip_time - {{browser_id}}"
    },
    {
     "expr": "stddev_over_time(webrtc_ice_candidate_pair_current_round_trip_time{browser_id=~\"$browserid\"}[2s])",
     "legendFormat": "stddev_round_trip_time - {{browser_id}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Control quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "venc_control_quality{browser_id=~\"$browserid\"}",
     "legendFormat": "venc_control_quality"
    }
   ]
  }
 ]
}