{
 "title": "Kafka Consumers",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Collaboration Server Pod",
    "query": "label_values(kafka_consumer_connection_count_connections, kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Fetch latency",
   "type": "graph",
   "description": "The average/max time taken for a fetch request.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_latency_avg_seconds{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Average {{kubernetes_pod_name}} {{client_id}}"
    },
    {
     "expr": "kafka_consumer_fetch_latency_max_seconds{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max {{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Fetch requests",
   "type": "graph",
   "description": "The number of fetch requests.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_consumer_fetch_total_requests_total{kubernetes_pod_name=~\"$pod\"}[$__interval])",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Fetch Size",
   "type": "graph",
   "description": "The average number of bytes fetched per request.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_size_avg_bytes{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Average {{kubernetes_pod_name}} {{client_id}}"
    },
    {
     "expr": "kafka_consumer_fetch_size_max_bytes{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max {{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Fetch throttle time",
   "type": "graph",
   "description": "The average throttle time in ms. When quotas are enabled, the broker may delay fetch requests in order to throttle a consumer which has exceeded its limit. This metric indicates how throttling time has been added to fetch requests on average.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_throttle_time_avg_seconds{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Average {{kubernetes_pod_name}} {{client_id}}"
    },
    {
     "expr": "kafka_consumer_fetch_throttle_time_avg_seconds{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max {{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Max Lag",
   "type": "graph",
   "description": "The maximum lag in terms of number of records for any partition in this window. An increasing value over time is your best indication that the consumer group is not keeping up with the producers.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_lag_max_records{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Records consumed",
   "type": "graph",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_consumer_records_consumed_total_records_total{kubernetes_pod_name=~\"$pod\"}[$__interval])",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Records per request",
   "type": "graph",
   "description": "The average number of records in each request.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_per_request_avg_records{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Bytes consumed",
   "type": "graph",
   "description": "The average number of bytes consumed per second.\n",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_consumer_bytes_consumed_total_bytes_total{kubernetes_pod_name=~\"$pod\"}[$__interval])",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Partitions assigned",
   "type": "graph",
   "description": "The number of partitions currently assigned to this consumer.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_assigned_partitions{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "graph",
   "description": "The number of commit calls per second.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_commit_rate_commits{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Group Syncs",
   "type": "graph",
   "description": "The number of group syncs per second. Group synchronization is the second and last phase of the rebalance protocol. A large value indicates group instability.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_sync_rate_syncs{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Group Joins",
   "type": "graph",
   "description": "The number of group joins per second. Group joining is the first phase of the rebalance protocol. A large value indicates that the consumer group is unstable and will likely be coupled with increased lag.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_join_rate_joins{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Heartbeat Rate",
   "type": "graph",
   "description": "The average number of heartbeats per second. After a rebalance, the consumer sends heartbeats to the coordinator to keep itself active in the group. You may see a lower rate than configured if the processing loop is taking more time to handle message batches. Usually this is OK as long as you see no increase in the join rate.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_heartbeat_rate_heartbeats{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Heartbeat Response Latency",
   "type": "graph",
   "description": "The max time taken to receive a response to a heartbeat request.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_heartbeat_response_time_max_seconds{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Commit Latency",
   "type": "graph",
   "description": "The average/max time taken for a commit request.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_commit_latency_avg_seconds{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Average {{kubernetes_pod_name}} {{client_id}}"
    },
    {
     "expr": "kafka_consumer_commit_latency_max_seconds{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max {{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Sync Latency",
   "type": "graph",
   "description": "The average/max time taken for a group sync.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_sync_time_avg_seconds{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Average {{kubernetes_pod_name}} {{client_id}}"
    },
    {
     "expr": "kafka_consumer_sync_time_max_seconds{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max {{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "graph",
   "description": "The current number of active connections.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_connection_count_connections{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Join Latency",
   "type": "graph",
   "description": "The average time taken for a group rejoin. This value can get as high as the configured session timeout for the consumer, but should usually be lower.\n\nThe max time taken for a group rejoin. This value should not get much higher than the configured session timeout for the consumer.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_join_time_avg_seconds{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Average {{kubernetes_pod_name}} {{client_id}}"
    },
    {
     "expr": "kafka_consumer_join_time_max_seconds{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max {{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "IO Wait",
   "type": "graph",
   "description": "The fraction of time the I/O thread spent waiting.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_io_wait_ratio{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "graph",
   "description": "The fraction of time the I/O thread spent doing I/O.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_io_ratio{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{client_id}}"
    }
   ]
  }
 ]
}