{
 "title": "Cluster Availability",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "zookeeper_pod",
    "query": "label_values(zookeeper_isleader,kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "$zookeeper_pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "zookeeper_pod" },
  {
   "title": "Instance Available",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{component=\"zookeeper\", kubernetes_pod_name=\"$zookeeper_pod\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (zookeeper_isleader{kubernetes_pod_name=\"$zookeeper_pod\"})*1",
     "legendFormat": "Is Leader"
    },
    {
     "expr": "sum (zookeeper_aliveClientConnections{kubernetes_pod_name=\"$zookeeper_pod\"})",
     "legendFormat": "Connected Clients"
    }
   ]
  },
  { "title": "$zookeeper_pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Instance Available",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{component=\"zookeeper\", kubernetes_pod_name=\"$zookeeper_pod\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (zookeeper_isleader{kubernetes_pod_name=\"$zookeeper_pod\"})*1",
     "legendFormat": "Is Leader"
    },
    {
     "expr": "sum (zookeeper_aliveClientConnections{kubernetes_pod_name=\"$zookeeper_pod\"})",
     "legendFormat": "Connected Clients"
    }
   ]
  },
  { "title": "$zookeeper_pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Instance Available",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{component=\"zookeeper\", kubernetes_pod_name=\"$zookeeper_pod\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (zookeeper_isleader{kubernetes_pod_name=\"$zookeeper_pod\"})*1",
     "legendFormat": "Is Leader"
    },
    {
     "expr": "sum (zookeeper_aliveClientConnections{kubernetes_pod_name=\"$zookeeper_pod\"})",
     "legendFormat": "Connected Clients"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka 1",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{component=\"kafka\",kubernetes_pod_name=\"kafka-0\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka 2",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{component=\"kafka\",kubernetes_pod_name=\"kafka-1\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka 3",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{component=\"kafka\",kubernetes_pod_name=\"kafka-2\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Collaboration Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Collaboration Server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (up{component=\"collaboration-server\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "HTTP Probe",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (probe_name) (probe_success)",
     "legendFormat": "{{probe_name}} Probe"
    }
   ]
  },
  {
   "title": "HTTP Probe Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{probe_name}} Probe " }
   ]
  }
 ]
}