{
 "title": "Database",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries and Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(eclipselink_Transactions_seconds_count[$__interval])",
     "legendFormat": "Transactions on {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(eclipselink_Query_seconds_count[$__interval])",
     "legendFormat": "Queries on {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Mean Query Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "eclipselink_Query_seconds_sum/eclipselink_Query_seconds_count",
     "legendFormat": " {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Connection Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Connection Pool Sizes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (persistenceunit,kubernetes_pod_name)(eclipselink_connectionpool_current)",
     "legendFormat": "{{persistenceunit}} on {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Datasource (Dis-)Connect",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(eclipselink_ConnectCalls_total[$__interval])",
     "legendFormat": "Connect on {{kubernetes_pod_name}}"
    },
    {
     "expr": "increase(eclipselink_DisconnectCalls_total[$__interval])",
     "legendFormat": "Disconnect on {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}