{
 "title": "MySQL / MariaDB",
 "description": "MySQL and MariaDB dashboard for the Prometheus mysqld-exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Global status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "min(mysql_up)" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(mysql_global_status_uptime)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections",
     "legendFormat": "Current"
    },
    {
     "expr": "mysql_global_variables_max_connections",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Disk Reads vs Writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mysql_global_status_innodb_data_reads[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(irate(mysql_global_status_innodb_data_writes[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Network Received vs Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mysql_global_status_bytes_received[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(mysql_global_status_bytes_sent[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Query Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mysql_global_status_commands_total[5m]) > 0) by (command)",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Running Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_global_status_threads_running)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Aborted Clients",
   "type": "graph",
   "description": "The number of connections that were aborted because the client died without closing the connection properly. See Section B.5.2.10, “Communication Errors and Aborted Connections”.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mysql_global_status_aborted_clients[30s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Aborted Connects",
   "type": "graph",
   "description": "The number of failed attempts to connect to the MySQL server. See Section B.5.2.10, “Communication Errors and Aborted Connections”.\n\nFor additional connection-related information, check the Connection_errors_xxx status variables and the host_cache table.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mysql_global_status_aborted_connects[$__interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Disk Usage ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_info_schema_table_size{component=\"data_length\"})",
     "legendFormat": "Tables"
    },
    {
     "expr": "sum(mysql_info_schema_table_size{component=\"index_length\"})",
     "legendFormat": "Indexes"
    }
   ]
  },
  {
   "title": "Table Rows",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_info_schema_table_rows)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}