{
 "title": "Database (HikariCP)",
 "description": "HikariCP Dashboard (Micrometer.io)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "kubernetes_pod_name",
    "label": "Pod",
    "query": "label_values(hikaricp_connections_min{application=\"$application\"}, kubernetes_pod_name)"
   },
   {
    "name": "hikaricp_pool_name",
    "label": "Hikari  Pool Name",
    "query": "label_values(hikaricp_connections_min{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}, pool)"
   }
  ]
 },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_idle{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Idle {{pool}} on {{kubernetes_pod_name}}"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Pending {{pool}} on {{kubernetes_pod_name}}"
    },
    {
     "expr": "hikaricp_connections_active{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Active {{pool}} on {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Max",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_max{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\", pool=~\"$hikaricp_pool_name\"})"
    }
   ]
  },
  {
   "title": "Min",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_min{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\", pool=~\"$hikaricp_pool_name\"})"
    }
   ]
  },
  {
   "title": "Usage Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_usage_seconds_sum{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\", pool=~\"$hikaricp_pool_name\"}[5m]) / rate(hikaricp_connections_usage_seconds_count{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Usage {{pool}} on {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Creation Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_creation_seconds_sum{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\", pool=~\"$hikaricp_pool_name\"}[5m]) / rate(hikaricp_connections_creation_seconds_count{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Creation {{pool}} on {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Acquire Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_acquire_seconds_sum{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\", pool=~\"$hikaricp_pool_name\"}[5m]) / rate(hikaricp_connections_acquire_seconds_count{application=\"$application\", kubernetes_pod_name=~\"$kubernetes_pod_name\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Acquire {{pool}} on {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}