{
 "title": "Unblu Application Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Unblu Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alarms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ALERTS) by (alertname)", "legendFormat": "{{alertname}}" }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(session_count{session_type=\"agent\"})",
     "legendFormat": "Agent"
    },
    {
     "expr": "sum(session_count{session_type=\"visitor\"})",
     "legendFormat": "Visitor"
    },
    {
     "expr": "sum(session_count{session_type=\"conversation\"})",
     "legendFormat": "Conversation"
    }
   ]
  },
  {
   "title": "Conversation Actions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action)(increase(collaboration_actions_total{recorder=\"ConversationRecorder\",action=~\"SEND_(.+)_MESSAGE|(.+)_CALL\"}[$__interval]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Nr. of Active Sockets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type)(socket_connections)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Session Logins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(session_logins_total[$__interval])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Collaboration Server Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"collaboration-server\"})"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(session_count{session_type=\"agent\"})"
    }
   ]
  },
  {
   "title": "Visitors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(session_count{session_type=\"visitor\"})"
    }
   ]
  },
  {
   "title": "Conversations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(session_count{session_type=\"conversation\"})"
    }
   ]
  },
  {
   "title": "WebSocket",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(socket_connections{type=\"websocket\"})"
    }
   ]
  },
  {
   "title": "Rendering Pods Busy",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"renderingservice\"})-sum(kube_deployment_status_replicas_available{deployment=\"renderingservice\"})"
    }
   ]
  },
  {
   "title": "Rendering Service Pool",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"renderingservice\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=\"renderingservice\"})",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Comet",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(socket_connections{type=\"comet\"})"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name)(irate(jetty_responses_total{application=\"unblu-collaboration-server\"}[$__interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum by (component)(irate(nginx_http_requests_total[$__interval]))",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "sum by (kubernetes_pod_name)(irate(haproxy_frontend_http_responses_total[$__interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jetty_requests_seconds_sum{component=\"collaboration-server\"}/jetty_requests_seconds_count{component=\"collaboration-server\"}",
     "legendFormat": "avg on {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (application, instance, status) (increase(jetty_responses_total{status=~\"4xx|5xx\"}[$__interval]))",
     "legendFormat": "{{application}} - {{instance}} - {{status}}"
    }
   ]
  },
  {
   "title": "RPC Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(rpc_call_total{component=\"collaboration-server\",status=\"successful\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "RPC Call Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rpc_call_duration_seconds_max{component=\"collaboration-server\"})",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rpc_call_duration_seconds_bucket{application=\"unblu-collaboration-server\"}[1m])) by (le))",
     "legendFormat": "99p"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(rpc_call_duration_seconds_bucket{application=\"unblu-collaboration-server\"}[1m])) by (le))",
     "legendFormat": "95p"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(rpc_call_duration_seconds_bucket{application=\"unblu-collaboration-server\"}[1m])) by (le))",
     "legendFormat": "90p"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(rpc_call_duration_seconds_bucket{application=\"unblu-collaboration-server\"}[1m])) by (le))",
     "legendFormat": "50p"
    }
   ]
  },
  {
   "title": "RPC Call Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(rpc_call_total{component=\"collaboration-server\",status=\"failed\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}} "
    }
   ]
  },
  {
   "title": "Visitor Snippet Reqests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(visitor_snippet_total[$__interval])) by (key)",
     "legendFormat": "key={{key}}"
    }
   ]
  },
  {
   "title": "Socket Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(socket_requests_total{application=\"unblu-collaboration-server\"}[1m])",
     "legendFormat": "{{instance}} - {{type}} - {{action}}"
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(cache_gets_total{result=\"miss\"}[1m]))",
     "legendFormat": "get/miss on {{instance}}"
    },
    {
     "expr": "sum by (instance)(rate(cache_puts_total[1m]))",
     "legendFormat": "put on {{instance}}"
    },
    {
     "expr": "sum by (instance)(rate(cache_evictions_total[1m]))",
     "legendFormat": "evict on {{instance}}"
    },
    {
     "expr": "sum by (instance)(rate(cache_gets_total{result=\"hit\"}[1m]))",
     "legendFormat": "get/hit on {{instance}}"
    },
    { "expr": "cache" }
   ]
  },
  {
   "title": "Caches Sizes",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cache_size",
     "legendFormat": "{{name}} on {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_free_bytes",
     "legendFormat": "{{kubernetes_pod_name}} [{{path}}]"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage",
     "legendFormat": "{{application}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 59 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "process_memory_pss_bytes",
     "legendFormat": "{{application}} - {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}