global:
  evaluation_interval: 1m
  scrape_interval: 10s
  scrape_timeout: 10s
rule_files:
- /etc/config/rules.yml
- /etc/config/alerts.yml
scrape_configs:
- job_name: kubernetes-services
  kubernetes_sd_configs:
  - namespaces:
      names:
      - $(PROM_NAMESPACE)
    role: service
  relabel_configs:
  - action: keep
    regex: true
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_scrape
  - action: replace
    regex: (https?)
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_scheme
    target_label: __scheme__
  - action: replace
    regex: (.+)
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_path
    target_label: __metrics_path__
  - action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    source_labels:
    - __address__
    - __meta_kubernetes_service_annotation_prometheus_io_port
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: kubernetes_namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_service_name
    target_label: kubernetes_name
- job_name: kubernetes-pods
  kubernetes_sd_configs:
  - namespaces:
      names:
      - $(PROM_NAMESPACE)
    role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    regex: (.+)
    target_label: __metrics_path__
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name
  - source_labels: [__meta_kubernetes_pod_label_component] # drop renderingservice pods, other pods are scraped in generic job
    regex: renderingservice
    action: drop
- job_name: kubernetes-rendering-pods
  kubernetes_sd_configs:
  - namespaces:
      names:
      - $(PROM_NAMESPACE)
    role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    regex: (.+)
    target_label: __metrics_path__
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name
  - source_labels: [__meta_kubernetes_pod_label_component] # only keep renderingservice pods, other pods are scraped in generic job
    regex: renderingservice
    action: keep
  # faster scraping for the renderingservice pods
  scrape_interval: 1s
  scrape_timeout: 1s
- job_name: blackbox
  metrics_path: /probe
  params:
    module: [http_2xx]
  kubernetes_sd_configs:
  - namespaces:
      names:
      - $(PROM_NAMESPACE)
    role: service
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels:
    - __address__
    - __meta_kubernetes_service_annotation_prometheus_io_path
    action: replace
    regex: (.+);(.+)
    replacement: ${1}${2}
    target_label: __param_target
  - replacement: blackbox-exporter:80
    target_label: __address__
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probename]
    target_label: probe_name
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    target_label: probe_path
  - source_labels: [__meta_kubernetes_service_name]
    target_label: kubernetes_service
  scrape_interval: 5s
  scrape_timeout: 5s

alerting:
  alertmanagers:
  - kubernetes_sd_configs:
      - namespaces:
          names:
          - $(PROM_NAMESPACE)
        role: pod
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace]
      regex:
      action: drop
    - source_labels: [__meta_kubernetes_pod_label_component]
      regex: alertmanager
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex:
      action: drop
