apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-k8s

bases:
# TODO change path to pull bases from GitHub
# - github.com/unblu-inc/unblu-kubernetes-base//collaboration-server
- ../collaboration-server
- ../renderingservice
- ../k8s-ingress
- ../k8s-prometheus
- ../grafana

patchesStrategicMerge:

resources:
- database-secret.yaml

configMapGenerator:
- name: collaboration-server-config
  behavior: merge
  files:
    - unblu-customer.properties

secretGenerator:
- name: ingress-tls
  behavior: merge
  files:
    - certs/tls.crt
    - certs/tls.key
  type: "kubernetes.io/tls"
