apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: singlenode

bases:
- ../collaboration-server-with-internal-db
- ../renderingservice
#- ../k8s-ingress

patchesStrategicMerge:
- singlenode.yaml

configMapGenerator:
- name: collaboration-server-config
  behavior: merge
  files:
    - unblu-customer.properties

images:
  - name: gcr.io/unblu-containerrepo-public/collaborationserver-centos7
    newName: gcr.io/unblu-containerrepo-private/collaborationserver-private-centos7
  - name: gcr.io/unblu-containerrepo-public/rendering-service
    newName: gcr.io/unblu-containerrepo-private/rendering-service
  - name: gcr.io/unblu-containerrepo-public/nginx-public-centos7
    newName: gcr.io/unblu-containerrepo-private/nginx-private-centos7
  - name: gcr.io/unblu-containerrepo-public/haproxy-public-centos7
    newName: gcr.io/unblu-containerrepo-private/haproxy-private-centos7

#secretGenerator:
#- name: ingress-tls
#  behavior: merge
#  files:
#    - certs/tls.crt
#    - certs/tls.key
#  type: "kubernetes.io/tls"