kind: Service
apiVersion: v1
metadata:
  name: haproxy
spec:
  type: ClusterIP
  ports:
  - name: 8080-tcp
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - haproxy
              topologyKey: kubernetes.io/hostname
      volumes:
      - name: haproxy-config
        configMap:
          name: haproxy-config
          defaultMode: 0777
      containers:
      - name: haproxy
        image: cluster/haproxy
        imagePullPolicy: Always
        args:
        - zookeeper:2181
        - unblu/service/worker
        - collaboration-server:9001
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10253
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10253
          initialDelaySeconds: 60
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 256Mi
        volumeMounts:
        - name: haproxy-config
          mountPath: /opt/
          readOnly: true
      - name: haproxy-exporter
        image: prom/haproxy-exporter
        imagePullPolicy: Always
        args:
        - --haproxy.scrape-uri
        - http://127.0.0.1:1936/;csv
        ports:
        - name: prom-exporter
          containerPort: 9101
        readinessProbe:
          httpGet:
            path: /metrics
            port: prom-exporter
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /metrics
            port: prom-exporter
          initialDelaySeconds: 15
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 50m
            memory: 64Mi
